<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.pixl8</groupId>
	<artifactId>socketio-lucee-jakarta</artifactId>
	<packaging>jar</packaging>
	<version>1.0.0</version>
	<name>SocketIO-Java Server Implementation with Lucee bindings</name>
	<url>http://maven.apache.org</url>
	<dependencies>
		<dependency>
			<groupId>org.eclipse.jetty.ee10</groupId>
			<artifactId>jetty-ee10-servlet</artifactId>
			<version>12.0.31</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.ee10.websocket</groupId>
			<artifactId>jetty-ee10-websocket-jakarta-server</artifactId>
			<version>12.0.11</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.websocket</groupId>
		    <artifactId>jetty-websocket-jetty-api</artifactId>
			<version>12.0.13</version>
		</dependency>
		<dependency>
			<groupId>org.eclipse.jetty.websocket</groupId>
			<artifactId>jetty-websocket-jetty-server</artifactId>
			<version>12.0.13</version>
		</dependency>
		<dependency>
			<groupId>org.json</groupId>
			<artifactId>json</artifactId>
			<version>20190722</version>
		</dependency>
		<dependency>
			<groupId>org.lucee</groupId>
			<artifactId>lucee</artifactId>
			<version>7.0.1.100</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>jakarta.servlet.jsp</groupId>
			<artifactId>jakarta.servlet.jsp-api</artifactId>
			<version>4.0.0</version>
			<scope>provided</scope>
		</dependency>
		<dependency>
			<groupId>com.squareup.okhttp3</groupId>
			<artifactId>okhttp</artifactId>
			<version>3.8.1</version>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.0</version>
				<configuration>
					<source>8</source>
					<target>8</target>
					<includes>
						<include>com/pixl8/socketiolucee/*.java</include>
						<include>io/socket/**/*.java</include>
					</includes>
				</configuration>
			</plugin>
			<plugin>
				<artifactId>maven-assembly-plugin</artifactId>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>single</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<descriptorRefs>
						<descriptorRef>jar-with-dependencies</descriptorRef>
					</descriptorRefs>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
